"""Returns an Object with information about blockheader ‘hash’"""
type BlockHeader {
    """block hash, same as provided"""
    hash: BlockHash
    """number of confirmations, or -1 if the block is not on the main chain"""
    confirmations: Int
    height: BlockHeight
    """block version"""
    version: Int
    """block version formatted in hexadecimal"""
    versionHex: String
    """merkle root"""
    merkleroot: String
    """block time in seconds since epoch"""
    time: Int
    """median block time in seconds since epoch"""
    mediantime: Int
    nonce: Int
    bits: String
    difficulty: Int
    """expected number of hashes required to produce the current chain"""
    chainwork: String
    """number of transactions in the block"""
    nTx: String
    """hash of the previous block"""
    previousblockhash: BlockHash
    """hash of the next block"""
    nextblockhash: BlockHash
    """string that is serialized, hex-encoded data of blockheader"""
    data: HexEncodedString
}
